/********************************************************************************
** Form generated from reading UI file 'playground_4.ui'
**
** Created by: Qt User Interface Compiler version 6.1.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PLAYGROUND_4_H
#define UI_PLAYGROUND_4_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFormLayout>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_playground
{
public:
    QWidget *centralwidget;
    QLabel *background;
    QPushButton *v1;
    QPushButton *v2;
    QPushButton *v3;
    QPushButton *v4;
    QPushButton *v5;
    QPushButton *v6;
    QPushButton *v17;
    QPushButton *v28;
    QPushButton *v39;
    QPushButton *v50;
    QPushButton *v61;
    QPushButton *v72;
    QPushButton *v84;
    QPushButton *v92;
    QPushButton *v7;
    QPushButton *v8;
    QPushButton *v9;
    QPushButton *v10;
    QPushButton *v11;
    QPushButton *v12;
    QPushButton *v13;
    QPushButton *v14;
    QPushButton *v15;
    QPushButton *v16;
    QPushButton *v18;
    QPushButton *v19;
    QPushButton *v20;
    QPushButton *v21;
    QPushButton *v22;
    QPushButton *v23;
    QPushButton *v24;
    QPushButton *v25;
    QPushButton *v26;
    QPushButton *v27;
    QPushButton *v29;
    QPushButton *v30;
    QPushButton *v31;
    QPushButton *v32;
    QPushButton *v33;
    QPushButton *v34;
    QPushButton *v35;
    QPushButton *v36;
    QPushButton *v37;
    QPushButton *v38;
    QPushButton *v40;
    QPushButton *v41;
    QPushButton *v42;
    QPushButton *v43;
    QPushButton *v44;
    QPushButton *v45;
    QPushButton *v46;
    QPushButton *v47;
    QPushButton *v48;
    QPushButton *v49;
    QPushButton *v51;
    QPushButton *v52;
    QPushButton *v53;
    QPushButton *v54;
    QPushButton *v55;
    QPushButton *v56;
    QPushButton *v57;
    QPushButton *v58;
    QPushButton *v59;
    QPushButton *v60;
    QPushButton *v62;
    QPushButton *v63;
    QPushButton *v64;
    QPushButton *v65;
    QPushButton *v66;
    QPushButton *v67;
    QPushButton *v68;
    QPushButton *v69;
    QPushButton *v70;
    QPushButton *v71;
    QPushButton *v73;
    QPushButton *v74;
    QPushButton *v75;
    QPushButton *v76;
    QPushButton *v77;
    QPushButton *v78;
    QPushButton *v79;
    QPushButton *v80;
    QPushButton *v81;
    QPushButton *v82;
    QPushButton *v83;
    QPushButton *v85;
    QPushButton *v86;
    QPushButton *v87;
    QPushButton *v88;
    QPushButton *v89;
    QPushButton *v90;
    QPushButton *v91;
    QLabel *guide;
    QWidget *verticalLayoutWidget_2;
    QVBoxLayout *players;
    QHBoxLayout *player1_info;
    QFormLayout *formLayout_3;
    QLabel *label_22;
    QLabel *label_30;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_31;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QVBoxLayout *player1;
    QLabel *picture1;
    QLabel *name1;
    QRadioButton *radioButton_3;
    QHBoxLayout *player2_info;
    QFormLayout *formLayout_4;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QVBoxLayout *player2;
    QLabel *picture2;
    QLabel *name2;
    QRadioButton *radioButton_4;
    QWidget *verticalLayoutWidget;
    QVBoxLayout *vl1;
    QLabel *label_43;
    QComboBox *building;
    QPushButton *ok;
    QWidget *verticalLayoutWidget_3;
    QVBoxLayout *verticalLayout_2;
    QHBoxLayout *player3_info;
    QFormLayout *formLayout_2;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_15;
    QVBoxLayout *verticalLayout;
    QLabel *picture3;
    QLabel *name3;
    QRadioButton *radioButton_2;
    QHBoxLayout *player4_info;
    QFormLayout *formLayout;
    QLabel *label_2;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_3;
    QVBoxLayout *player4;
    QLabel *picture4;
    QLabel *name4;
    QRadioButton *radioButton;
    QPushButton *dice;
    QPushButton *robber;
    QPushButton *end;
    QPushButton *trade;
    QPushButton *developmentcard;
    QPushButton *t9;
    QPushButton *t21;
    QPushButton *t5;
    QPushButton *t1;
    QPushButton *t18;
    QPushButton *t10;
    QPushButton *t25;
    QPushButton *t8;
    QPushButton *t7;
    QPushButton *t13;
    QPushButton *t20;
    QPushButton *t24;
    QPushButton *t27;
    QPushButton *t16;
    QPushButton *t12;
    QPushButton *t17;
    QPushButton *t19;
    QPushButton *t14;
    QPushButton *t4;
    QPushButton *t6;
    QPushButton *t11;
    QPushButton *t23;
    QPushButton *t28;
    QPushButton *t26;
    QPushButton *t2;
    QPushButton *t3;
    QPushButton *t22;
    QPushButton *t15;
    QPushButton *b5;
    QPushButton *b7;
    QPushButton *b10;
    QPushButton *b1;
    QPushButton *b3;
    QPushButton *b4;
    QPushButton *b13;
    QPushButton *b11;
    QPushButton *b6;
    QPushButton *b8;
    QPushButton *b2;
    QPushButton *b12;
    QPushButton *b9;
    QPushButton *e1;
    QPushButton *e2;
    QPushButton *e3;
    QPushButton *e4;
    QPushButton *e5;
    QPushButton *e6;
    QPushButton *e7;
    QPushButton *e8;
    QPushButton *e9;
    QPushButton *e10;
    QPushButton *e11;
    QPushButton *e12;
    QPushButton *e13;
    QPushButton *e14;
    QPushButton *e15;
    QPushButton *e16;
    QPushButton *e17;
    QPushButton *e18;
    QPushButton *e19;
    QPushButton *e20;
    QPushButton *e21;
    QPushButton *e22;
    QPushButton *e23;
    QPushButton *e24;
    QPushButton *e25;
    QPushButton *e26;
    QPushButton *e27;
    QPushButton *e28;
    QPushButton *e29;
    QPushButton *e30;
    QPushButton *e31;
    QPushButton *e32;
    QPushButton *e33;
    QPushButton *e34;
    QPushButton *e35;
    QPushButton *e36;
    QPushButton *e37;
    QPushButton *e38;
    QPushButton *e39;
    QPushButton *e40;
    QPushButton *e41;
    QPushButton *e42;
    QPushButton *e43;
    QPushButton *e44;
    QPushButton *e45;
    QPushButton *e46;
    QPushButton *e47;
    QPushButton *e48;
    QPushButton *e49;
    QPushButton *e50;
    QPushButton *e51;
    QPushButton *e52;
    QPushButton *e53;
    QPushButton *e54;
    QPushButton *e55;
    QPushButton *e56;
    QPushButton *e57;
    QPushButton *e58;
    QPushButton *e59;
    QPushButton *e60;
    QPushButton *e61;
    QPushButton *e62;
    QPushButton *e63;
    QPushButton *e64;
    QPushButton *e65;
    QPushButton *e66;
    QPushButton *e67;
    QPushButton *e68;
    QPushButton *e69;
    QPushButton *e70;
    QPushButton *e71;
    QPushButton *e72;
    QPushButton *e73;
    QPushButton *e74;
    QPushButton *e75;
    QPushButton *e76;
    QPushButton *e77;
    QPushButton *e78;
    QPushButton *e79;
    QPushButton *e80;
    QPushButton *e81;
    QPushButton *e82;
    QPushButton *e83;
    QPushButton *e84;
    QPushButton *e85;
    QPushButton *e86;
    QPushButton *e87;
    QPushButton *e88;
    QPushButton *e89;
    QPushButton *e90;
    QPushButton *e91;
    QPushButton *e92;
    QPushButton *e93;
    QPushButton *e94;
    QPushButton *e95;
    QPushButton *e96;
    QPushButton *e97;
    QPushButton *e98;
    QPushButton *e99;
    QPushButton *e100;
    QPushButton *e101;
    QPushButton *e102;
    QPushButton *e103;
    QPushButton *e104;
    QPushButton *e105;
    QPushButton *e106;
    QPushButton *e107;
    QPushButton *e108;
    QPushButton *e109;
    QPushButton *e110;
    QPushButton *e111;
    QPushButton *e112;
    QPushButton *e113;
    QPushButton *e114;
    QPushButton *e115;
    QPushButton *e116;
    QPushButton *e117;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *playground)
    {
        if (playground->objectName().isEmpty())
            playground->setObjectName(QString::fromUtf8("playground"));
        playground->resize(1010, 642);
        centralwidget = new QWidget(playground);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        background = new QLabel(centralwidget);
        background->setObjectName(QString::fromUtf8("background"));
        background->setEnabled(true);
        background->setGeometry(QRect(0, -30, 1001, 651));
        background->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/catan.jpg")));
        v1 = new QPushButton(centralwidget);
        v1->setObjectName(QString::fromUtf8("v1"));
        v1->setGeometry(QRect(340, 100, 21, 21));
        v1->setFlat(true);
        v2 = new QPushButton(centralwidget);
        v2->setObjectName(QString::fromUtf8("v2"));
        v2->setGeometry(QRect(400, 100, 21, 21));
        v2->setFlat(true);
        v3 = new QPushButton(centralwidget);
        v3->setObjectName(QString::fromUtf8("v3"));
        v3->setGeometry(QRect(470, 100, 21, 21));
        v3->setFlat(true);
        v4 = new QPushButton(centralwidget);
        v4->setObjectName(QString::fromUtf8("v4"));
        v4->setGeometry(QRect(310, 110, 21, 21));
        v4->setFlat(true);
        v5 = new QPushButton(centralwidget);
        v5->setObjectName(QString::fromUtf8("v5"));
        v5->setGeometry(QRect(370, 110, 21, 21));
        v5->setFlat(true);
        v6 = new QPushButton(centralwidget);
        v6->setObjectName(QString::fromUtf8("v6"));
        v6->setGeometry(QRect(440, 110, 21, 21));
        v6->setFlat(true);
        v17 = new QPushButton(centralwidget);
        v17->setObjectName(QString::fromUtf8("v17"));
        v17->setGeometry(QRect(280, 190, 21, 21));
        v17->setFlat(true);
        v28 = new QPushButton(centralwidget);
        v28->setObjectName(QString::fromUtf8("v28"));
        v28->setGeometry(QRect(240, 240, 21, 21));
        v28->setFlat(true);
        v39 = new QPushButton(centralwidget);
        v39->setObjectName(QString::fromUtf8("v39"));
        v39->setGeometry(QRect(270, 290, 21, 21));
        v39->setFlat(true);
        v50 = new QPushButton(centralwidget);
        v50->setObjectName(QString::fromUtf8("v50"));
        v50->setGeometry(QRect(430, 340, 21, 21));
        v50->setFlat(true);
        v61 = new QPushButton(centralwidget);
        v61->setObjectName(QString::fromUtf8("v61"));
        v61->setGeometry(QRect(660, 160, 21, 21));
        v61->setFlat(true);
        v72 = new QPushButton(centralwidget);
        v72->setObjectName(QString::fromUtf8("v72"));
        v72->setGeometry(QRect(730, 290, 21, 21));
        v72->setFlat(true);
        v84 = new QPushButton(centralwidget);
        v84->setObjectName(QString::fromUtf8("v84"));
        v84->setGeometry(QRect(660, 390, 21, 21));
        v84->setFlat(true);
        v92 = new QPushButton(centralwidget);
        v92->setObjectName(QString::fromUtf8("v92"));
        v92->setGeometry(QRect(460, 470, 21, 21));
        v92->setFlat(true);
        v7 = new QPushButton(centralwidget);
        v7->setObjectName(QString::fromUtf8("v7"));
        v7->setGeometry(QRect(500, 110, 21, 21));
        v7->setFlat(true);
        v8 = new QPushButton(centralwidget);
        v8->setObjectName(QString::fromUtf8("v8"));
        v8->setGeometry(QRect(310, 140, 21, 21));
        v8->setFlat(true);
        v9 = new QPushButton(centralwidget);
        v9->setObjectName(QString::fromUtf8("v9"));
        v9->setGeometry(QRect(370, 140, 21, 21));
        v9->setFlat(true);
        v10 = new QPushButton(centralwidget);
        v10->setObjectName(QString::fromUtf8("v10"));
        v10->setGeometry(QRect(430, 140, 21, 21));
        v10->setFlat(true);
        v11 = new QPushButton(centralwidget);
        v11->setObjectName(QString::fromUtf8("v11"));
        v11->setGeometry(QRect(500, 140, 21, 21));
        v11->setFlat(true);
        v12 = new QPushButton(centralwidget);
        v12->setObjectName(QString::fromUtf8("v12"));
        v12->setGeometry(QRect(280, 160, 21, 21));
        v12->setFlat(true);
        v13 = new QPushButton(centralwidget);
        v13->setObjectName(QString::fromUtf8("v13"));
        v13->setGeometry(QRect(340, 160, 21, 21));
        v13->setFlat(true);
        v14 = new QPushButton(centralwidget);
        v14->setObjectName(QString::fromUtf8("v14"));
        v14->setGeometry(QRect(400, 160, 21, 21));
        v14->setFlat(true);
        v15 = new QPushButton(centralwidget);
        v15->setObjectName(QString::fromUtf8("v15"));
        v15->setGeometry(QRect(470, 160, 21, 21));
        v15->setFlat(true);
        v16 = new QPushButton(centralwidget);
        v16->setObjectName(QString::fromUtf8("v16"));
        v16->setGeometry(QRect(530, 160, 21, 21));
        v16->setFlat(true);
        v18 = new QPushButton(centralwidget);
        v18->setObjectName(QString::fromUtf8("v18"));
        v18->setGeometry(QRect(340, 190, 21, 21));
        v18->setFlat(true);
        v19 = new QPushButton(centralwidget);
        v19->setObjectName(QString::fromUtf8("v19"));
        v19->setGeometry(QRect(400, 190, 21, 21));
        v19->setFlat(true);
        v20 = new QPushButton(centralwidget);
        v20->setObjectName(QString::fromUtf8("v20"));
        v20->setGeometry(QRect(470, 190, 21, 21));
        v20->setFlat(true);
        v21 = new QPushButton(centralwidget);
        v21->setObjectName(QString::fromUtf8("v21"));
        v21->setGeometry(QRect(530, 190, 21, 21));
        v21->setFlat(true);
        v22 = new QPushButton(centralwidget);
        v22->setObjectName(QString::fromUtf8("v22"));
        v22->setGeometry(QRect(240, 200, 21, 21));
        v22->setFlat(true);
        v23 = new QPushButton(centralwidget);
        v23->setObjectName(QString::fromUtf8("v23"));
        v23->setGeometry(QRect(310, 200, 21, 21));
        v23->setFlat(true);
        v24 = new QPushButton(centralwidget);
        v24->setObjectName(QString::fromUtf8("v24"));
        v24->setGeometry(QRect(370, 200, 21, 21));
        v24->setFlat(true);
        v25 = new QPushButton(centralwidget);
        v25->setObjectName(QString::fromUtf8("v25"));
        v25->setGeometry(QRect(430, 200, 21, 21));
        v25->setFlat(true);
        v26 = new QPushButton(centralwidget);
        v26->setObjectName(QString::fromUtf8("v26"));
        v26->setGeometry(QRect(500, 200, 21, 21));
        v26->setFlat(true);
        v27 = new QPushButton(centralwidget);
        v27->setObjectName(QString::fromUtf8("v27"));
        v27->setGeometry(QRect(560, 200, 21, 21));
        v27->setFlat(true);
        v29 = new QPushButton(centralwidget);
        v29->setObjectName(QString::fromUtf8("v29"));
        v29->setGeometry(QRect(300, 240, 21, 21));
        v29->setFlat(true);
        v30 = new QPushButton(centralwidget);
        v30->setObjectName(QString::fromUtf8("v30"));
        v30->setGeometry(QRect(370, 240, 21, 21));
        v30->setFlat(true);
        v31 = new QPushButton(centralwidget);
        v31->setObjectName(QString::fromUtf8("v31"));
        v31->setGeometry(QRect(430, 240, 21, 21));
        v31->setFlat(true);
        v32 = new QPushButton(centralwidget);
        v32->setObjectName(QString::fromUtf8("v32"));
        v32->setGeometry(QRect(500, 240, 21, 21));
        v32->setFlat(true);
        v33 = new QPushButton(centralwidget);
        v33->setObjectName(QString::fromUtf8("v33"));
        v33->setGeometry(QRect(560, 240, 21, 21));
        v33->setFlat(true);
        v34 = new QPushButton(centralwidget);
        v34->setObjectName(QString::fromUtf8("v34"));
        v34->setGeometry(QRect(270, 250, 21, 21));
        v34->setFlat(true);
        v35 = new QPushButton(centralwidget);
        v35->setObjectName(QString::fromUtf8("v35"));
        v35->setGeometry(QRect(330, 250, 21, 21));
        v35->setFlat(true);
        v36 = new QPushButton(centralwidget);
        v36->setObjectName(QString::fromUtf8("v36"));
        v36->setGeometry(QRect(400, 250, 21, 21));
        v36->setFlat(true);
        v37 = new QPushButton(centralwidget);
        v37->setObjectName(QString::fromUtf8("v37"));
        v37->setGeometry(QRect(460, 250, 21, 21));
        v37->setFlat(true);
        v38 = new QPushButton(centralwidget);
        v38->setObjectName(QString::fromUtf8("v38"));
        v38->setGeometry(QRect(530, 250, 21, 21));
        v38->setFlat(true);
        v40 = new QPushButton(centralwidget);
        v40->setObjectName(QString::fromUtf8("v40"));
        v40->setGeometry(QRect(330, 290, 21, 21));
        v40->setFlat(true);
        v41 = new QPushButton(centralwidget);
        v41->setObjectName(QString::fromUtf8("v41"));
        v41->setGeometry(QRect(400, 290, 21, 21));
        v41->setFlat(true);
        v42 = new QPushButton(centralwidget);
        v42->setObjectName(QString::fromUtf8("v42"));
        v42->setGeometry(QRect(460, 290, 21, 21));
        v42->setFlat(true);
        v43 = new QPushButton(centralwidget);
        v43->setObjectName(QString::fromUtf8("v43"));
        v43->setGeometry(QRect(530, 290, 21, 21));
        v43->setFlat(true);
        v44 = new QPushButton(centralwidget);
        v44->setObjectName(QString::fromUtf8("v44"));
        v44->setGeometry(QRect(300, 300, 21, 21));
        v44->setFlat(true);
        v45 = new QPushButton(centralwidget);
        v45->setObjectName(QString::fromUtf8("v45"));
        v45->setGeometry(QRect(370, 300, 21, 21));
        v45->setFlat(true);
        v46 = new QPushButton(centralwidget);
        v46->setObjectName(QString::fromUtf8("v46"));
        v46->setGeometry(QRect(430, 300, 21, 21));
        v46->setFlat(true);
        v47 = new QPushButton(centralwidget);
        v47->setObjectName(QString::fromUtf8("v47"));
        v47->setGeometry(QRect(500, 300, 21, 21));
        v47->setFlat(true);
        v48 = new QPushButton(centralwidget);
        v48->setObjectName(QString::fromUtf8("v48"));
        v48->setGeometry(QRect(300, 340, 21, 21));
        v48->setFlat(true);
        v49 = new QPushButton(centralwidget);
        v49->setObjectName(QString::fromUtf8("v49"));
        v49->setGeometry(QRect(360, 340, 21, 21));
        v49->setFlat(true);
        v51 = new QPushButton(centralwidget);
        v51->setObjectName(QString::fromUtf8("v51"));
        v51->setGeometry(QRect(500, 340, 21, 21));
        v51->setFlat(true);
        v52 = new QPushButton(centralwidget);
        v52->setObjectName(QString::fromUtf8("v52"));
        v52->setGeometry(QRect(330, 360, 21, 21));
        v52->setFlat(true);
        v53 = new QPushButton(centralwidget);
        v53->setObjectName(QString::fromUtf8("v53"));
        v53->setGeometry(QRect(400, 360, 21, 21));
        v53->setFlat(true);
        v54 = new QPushButton(centralwidget);
        v54->setObjectName(QString::fromUtf8("v54"));
        v54->setGeometry(QRect(460, 360, 21, 21));
        v54->setFlat(true);
        v55 = new QPushButton(centralwidget);
        v55->setObjectName(QString::fromUtf8("v55"));
        v55->setGeometry(QRect(590, 100, 21, 21));
        v55->setFlat(true);
        v56 = new QPushButton(centralwidget);
        v56->setObjectName(QString::fromUtf8("v56"));
        v56->setGeometry(QRect(560, 110, 21, 21));
        v56->setFlat(true);
        v57 = new QPushButton(centralwidget);
        v57->setObjectName(QString::fromUtf8("v57"));
        v57->setGeometry(QRect(620, 110, 21, 21));
        v57->setFlat(true);
        v58 = new QPushButton(centralwidget);
        v58->setObjectName(QString::fromUtf8("v58"));
        v58->setGeometry(QRect(560, 140, 21, 21));
        v58->setFlat(true);
        v59 = new QPushButton(centralwidget);
        v59->setObjectName(QString::fromUtf8("v59"));
        v59->setGeometry(QRect(620, 140, 21, 21));
        v59->setFlat(true);
        v60 = new QPushButton(centralwidget);
        v60->setObjectName(QString::fromUtf8("v60"));
        v60->setGeometry(QRect(590, 160, 21, 21));
        v60->setFlat(true);
        v62 = new QPushButton(centralwidget);
        v62->setObjectName(QString::fromUtf8("v62"));
        v62->setGeometry(QRect(590, 190, 21, 21));
        v62->setFlat(true);
        v63 = new QPushButton(centralwidget);
        v63->setObjectName(QString::fromUtf8("v63"));
        v63->setGeometry(QRect(660, 190, 21, 21));
        v63->setFlat(true);
        v64 = new QPushButton(centralwidget);
        v64->setObjectName(QString::fromUtf8("v64"));
        v64->setGeometry(QRect(620, 210, 21, 21));
        v64->setFlat(true);
        v65 = new QPushButton(centralwidget);
        v65->setObjectName(QString::fromUtf8("v65"));
        v65->setGeometry(QRect(690, 210, 21, 21));
        v65->setFlat(true);
        v66 = new QPushButton(centralwidget);
        v66->setObjectName(QString::fromUtf8("v66"));
        v66->setGeometry(QRect(630, 240, 21, 21));
        v66->setFlat(true);
        v67 = new QPushButton(centralwidget);
        v67->setObjectName(QString::fromUtf8("v67"));
        v67->setGeometry(QRect(690, 240, 21, 21));
        v67->setFlat(true);
        v68 = new QPushButton(centralwidget);
        v68->setObjectName(QString::fromUtf8("v68"));
        v68->setGeometry(QRect(660, 260, 21, 21));
        v68->setFlat(true);
        v69 = new QPushButton(centralwidget);
        v69->setObjectName(QString::fromUtf8("v69"));
        v69->setGeometry(QRect(730, 260, 21, 21));
        v69->setFlat(true);
        v70 = new QPushButton(centralwidget);
        v70->setObjectName(QString::fromUtf8("v70"));
        v70->setGeometry(QRect(600, 290, 21, 21));
        v70->setFlat(true);
        v71 = new QPushButton(centralwidget);
        v71->setObjectName(QString::fromUtf8("v71"));
        v71->setGeometry(QRect(660, 290, 21, 21));
        v71->setFlat(true);
        v73 = new QPushButton(centralwidget);
        v73->setObjectName(QString::fromUtf8("v73"));
        v73->setGeometry(QRect(560, 300, 21, 21));
        v73->setFlat(true);
        v74 = new QPushButton(centralwidget);
        v74->setObjectName(QString::fromUtf8("v74"));
        v74->setGeometry(QRect(630, 300, 21, 21));
        v74->setFlat(true);
        v75 = new QPushButton(centralwidget);
        v75->setObjectName(QString::fromUtf8("v75"));
        v75->setGeometry(QRect(700, 300, 21, 21));
        v75->setFlat(true);
        v76 = new QPushButton(centralwidget);
        v76->setObjectName(QString::fromUtf8("v76"));
        v76->setGeometry(QRect(560, 340, 21, 21));
        v76->setFlat(true);
        v77 = new QPushButton(centralwidget);
        v77->setObjectName(QString::fromUtf8("v77"));
        v77->setGeometry(QRect(630, 340, 21, 21));
        v77->setFlat(true);
        v78 = new QPushButton(centralwidget);
        v78->setObjectName(QString::fromUtf8("v78"));
        v78->setGeometry(QRect(700, 340, 21, 21));
        v78->setFlat(true);
        v79 = new QPushButton(centralwidget);
        v79->setObjectName(QString::fromUtf8("v79"));
        v79->setGeometry(QRect(530, 360, 21, 21));
        v79->setFlat(true);
        v80 = new QPushButton(centralwidget);
        v80->setObjectName(QString::fromUtf8("v80"));
        v80->setGeometry(QRect(600, 360, 21, 21));
        v80->setFlat(true);
        v81 = new QPushButton(centralwidget);
        v81->setObjectName(QString::fromUtf8("v81"));
        v81->setGeometry(QRect(660, 360, 21, 21));
        v81->setFlat(true);
        v82 = new QPushButton(centralwidget);
        v82->setObjectName(QString::fromUtf8("v82"));
        v82->setGeometry(QRect(530, 390, 21, 21));
        v82->setFlat(true);
        v83 = new QPushButton(centralwidget);
        v83->setObjectName(QString::fromUtf8("v83"));
        v83->setGeometry(QRect(600, 390, 21, 21));
        v83->setFlat(true);
        v85 = new QPushButton(centralwidget);
        v85->setObjectName(QString::fromUtf8("v85"));
        v85->setGeometry(QRect(560, 410, 21, 21));
        v85->setFlat(true);
        v86 = new QPushButton(centralwidget);
        v86->setObjectName(QString::fromUtf8("v86"));
        v86->setGeometry(QRect(630, 410, 21, 21));
        v86->setFlat(true);
        v87 = new QPushButton(centralwidget);
        v87->setObjectName(QString::fromUtf8("v87"));
        v87->setGeometry(QRect(460, 390, 21, 21));
        v87->setFlat(true);
        v88 = new QPushButton(centralwidget);
        v88->setObjectName(QString::fromUtf8("v88"));
        v88->setGeometry(QRect(430, 410, 21, 21));
        v88->setFlat(true);
        v89 = new QPushButton(centralwidget);
        v89->setObjectName(QString::fromUtf8("v89"));
        v89->setGeometry(QRect(500, 410, 21, 21));
        v89->setFlat(true);
        v90 = new QPushButton(centralwidget);
        v90->setObjectName(QString::fromUtf8("v90"));
        v90->setGeometry(QRect(430, 450, 21, 21));
        v90->setFlat(true);
        v91 = new QPushButton(centralwidget);
        v91->setObjectName(QString::fromUtf8("v91"));
        v91->setGeometry(QRect(500, 450, 21, 21));
        v91->setFlat(true);
        guide = new QLabel(centralwidget);
        guide->setObjectName(QString::fromUtf8("guide"));
        guide->setGeometry(QRect(750, 440, 231, 141));
        guide->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/hani8.jpg")));
        verticalLayoutWidget_2 = new QWidget(centralwidget);
        verticalLayoutWidget_2->setObjectName(QString::fromUtf8("verticalLayoutWidget_2"));
        verticalLayoutWidget_2->setGeometry(QRect(800, 0, 197, 311));
        players = new QVBoxLayout(verticalLayoutWidget_2);
        players->setSpacing(7);
        players->setObjectName(QString::fromUtf8("players"));
        players->setContentsMargins(0, 0, 0, 0);
        player1_info = new QHBoxLayout();
        player1_info->setObjectName(QString::fromUtf8("player1_info"));
        formLayout_3 = new QFormLayout();
        formLayout_3->setObjectName(QString::fromUtf8("formLayout_3"));
        label_22 = new QLabel(verticalLayoutWidget_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));

        formLayout_3->setWidget(0, QFormLayout::LabelRole, label_22);

        label_30 = new QLabel(verticalLayoutWidget_2);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/shaep.png")));

        formLayout_3->setWidget(0, QFormLayout::FieldRole, label_30);

        label_23 = new QLabel(verticalLayoutWidget_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));

        formLayout_3->setWidget(1, QFormLayout::LabelRole, label_23);

        label_24 = new QLabel(verticalLayoutWidget_2);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/wheat.png")));

        formLayout_3->setWidget(1, QFormLayout::FieldRole, label_24);

        label_31 = new QLabel(verticalLayoutWidget_2);
        label_31->setObjectName(QString::fromUtf8("label_31"));

        formLayout_3->setWidget(2, QFormLayout::LabelRole, label_31);

        label_25 = new QLabel(verticalLayoutWidget_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/stone.png")));

        formLayout_3->setWidget(2, QFormLayout::FieldRole, label_25);

        label_26 = new QLabel(verticalLayoutWidget_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));

        formLayout_3->setWidget(3, QFormLayout::LabelRole, label_26);

        label_27 = new QLabel(verticalLayoutWidget_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/wood.png")));

        formLayout_3->setWidget(3, QFormLayout::FieldRole, label_27);

        label_28 = new QLabel(verticalLayoutWidget_2);
        label_28->setObjectName(QString::fromUtf8("label_28"));

        formLayout_3->setWidget(4, QFormLayout::LabelRole, label_28);

        label_29 = new QLabel(verticalLayoutWidget_2);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/brick1.png")));

        formLayout_3->setWidget(4, QFormLayout::FieldRole, label_29);


        player1_info->addLayout(formLayout_3);

        player1 = new QVBoxLayout();
        player1->setObjectName(QString::fromUtf8("player1"));
        picture1 = new QLabel(verticalLayoutWidget_2);
        picture1->setObjectName(QString::fromUtf8("picture1"));
        picture1->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/player4.jpg")));

        player1->addWidget(picture1);

        name1 = new QLabel(verticalLayoutWidget_2);
        name1->setObjectName(QString::fromUtf8("name1"));

        player1->addWidget(name1);

        radioButton_3 = new QRadioButton(verticalLayoutWidget_2);
        radioButton_3->setObjectName(QString::fromUtf8("radioButton_3"));
        radioButton_3->setEnabled(false);

        player1->addWidget(radioButton_3);


        player1_info->addLayout(player1);


        players->addLayout(player1_info);

        player2_info = new QHBoxLayout();
        player2_info->setObjectName(QString::fromUtf8("player2_info"));
        formLayout_4 = new QFormLayout();
        formLayout_4->setObjectName(QString::fromUtf8("formLayout_4"));
        label_32 = new QLabel(verticalLayoutWidget_2);
        label_32->setObjectName(QString::fromUtf8("label_32"));

        formLayout_4->setWidget(0, QFormLayout::LabelRole, label_32);

        label_33 = new QLabel(verticalLayoutWidget_2);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/shaep.png")));

        formLayout_4->setWidget(0, QFormLayout::FieldRole, label_33);

        label_34 = new QLabel(verticalLayoutWidget_2);
        label_34->setObjectName(QString::fromUtf8("label_34"));

        formLayout_4->setWidget(1, QFormLayout::LabelRole, label_34);

        label_35 = new QLabel(verticalLayoutWidget_2);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/wheat.png")));

        formLayout_4->setWidget(1, QFormLayout::FieldRole, label_35);

        label_36 = new QLabel(verticalLayoutWidget_2);
        label_36->setObjectName(QString::fromUtf8("label_36"));

        formLayout_4->setWidget(2, QFormLayout::LabelRole, label_36);

        label_37 = new QLabel(verticalLayoutWidget_2);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/stone.png")));

        formLayout_4->setWidget(2, QFormLayout::FieldRole, label_37);

        label_38 = new QLabel(verticalLayoutWidget_2);
        label_38->setObjectName(QString::fromUtf8("label_38"));

        formLayout_4->setWidget(3, QFormLayout::LabelRole, label_38);

        label_39 = new QLabel(verticalLayoutWidget_2);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/wood.png")));

        formLayout_4->setWidget(3, QFormLayout::FieldRole, label_39);

        label_40 = new QLabel(verticalLayoutWidget_2);
        label_40->setObjectName(QString::fromUtf8("label_40"));

        formLayout_4->setWidget(4, QFormLayout::LabelRole, label_40);

        label_41 = new QLabel(verticalLayoutWidget_2);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/brick1.png")));

        formLayout_4->setWidget(4, QFormLayout::FieldRole, label_41);


        player2_info->addLayout(formLayout_4);

        player2 = new QVBoxLayout();
        player2->setObjectName(QString::fromUtf8("player2"));
        picture2 = new QLabel(verticalLayoutWidget_2);
        picture2->setObjectName(QString::fromUtf8("picture2"));
        picture2->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/player2.jpg")));

        player2->addWidget(picture2);

        name2 = new QLabel(verticalLayoutWidget_2);
        name2->setObjectName(QString::fromUtf8("name2"));

        player2->addWidget(name2);

        radioButton_4 = new QRadioButton(verticalLayoutWidget_2);
        radioButton_4->setObjectName(QString::fromUtf8("radioButton_4"));
        radioButton_4->setEnabled(false);

        player2->addWidget(radioButton_4);


        player2_info->addLayout(player2);


        players->addLayout(player2_info);

        verticalLayoutWidget = new QWidget(centralwidget);
        verticalLayoutWidget->setObjectName(QString::fromUtf8("verticalLayoutWidget"));
        verticalLayoutWidget->setGeometry(QRect(750, 340, 241, 88));
        vl1 = new QVBoxLayout(verticalLayoutWidget);
        vl1->setObjectName(QString::fromUtf8("vl1"));
        vl1->setContentsMargins(0, 0, 0, 0);
        label_43 = new QLabel(verticalLayoutWidget);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        QFont font;
        font.setFamilies({QString::fromUtf8("Bodoni MT")});
        font.setPointSize(11);
        label_43->setFont(font);

        vl1->addWidget(label_43);

        building = new QComboBox(verticalLayoutWidget);
        building->setObjectName(QString::fromUtf8("building"));

        vl1->addWidget(building);

        ok = new QPushButton(verticalLayoutWidget);
        ok->setObjectName(QString::fromUtf8("ok"));

        vl1->addWidget(ok);

        verticalLayoutWidget_3 = new QWidget(centralwidget);
        verticalLayoutWidget_3->setObjectName(QString::fromUtf8("verticalLayoutWidget_3"));
        verticalLayoutWidget_3->setGeometry(QRect(0, 270, 201, 309));
        verticalLayout_2 = new QVBoxLayout(verticalLayoutWidget_3);
        verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
        verticalLayout_2->setContentsMargins(0, 0, 0, 0);
        player3_info = new QHBoxLayout();
        player3_info->setObjectName(QString::fromUtf8("player3_info"));
        formLayout_2 = new QFormLayout();
        formLayout_2->setObjectName(QString::fromUtf8("formLayout_2"));
        label_12 = new QLabel(verticalLayoutWidget_3);
        label_12->setObjectName(QString::fromUtf8("label_12"));

        formLayout_2->setWidget(0, QFormLayout::LabelRole, label_12);

        label_13 = new QLabel(verticalLayoutWidget_3);
        label_13->setObjectName(QString::fromUtf8("label_13"));

        formLayout_2->setWidget(1, QFormLayout::LabelRole, label_13);

        label_14 = new QLabel(verticalLayoutWidget_3);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/wheat.png")));

        formLayout_2->setWidget(1, QFormLayout::FieldRole, label_14);

        label_16 = new QLabel(verticalLayoutWidget_3);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/stone.png")));

        formLayout_2->setWidget(2, QFormLayout::FieldRole, label_16);

        label_17 = new QLabel(verticalLayoutWidget_3);
        label_17->setObjectName(QString::fromUtf8("label_17"));

        formLayout_2->setWidget(3, QFormLayout::LabelRole, label_17);

        label_18 = new QLabel(verticalLayoutWidget_3);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/wood.png")));

        formLayout_2->setWidget(3, QFormLayout::FieldRole, label_18);

        label_19 = new QLabel(verticalLayoutWidget_3);
        label_19->setObjectName(QString::fromUtf8("label_19"));

        formLayout_2->setWidget(4, QFormLayout::LabelRole, label_19);

        label_20 = new QLabel(verticalLayoutWidget_3);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/brick1.png")));

        formLayout_2->setWidget(4, QFormLayout::FieldRole, label_20);

        label_21 = new QLabel(verticalLayoutWidget_3);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/shaep.png")));

        formLayout_2->setWidget(0, QFormLayout::FieldRole, label_21);

        label_15 = new QLabel(verticalLayoutWidget_3);
        label_15->setObjectName(QString::fromUtf8("label_15"));

        formLayout_2->setWidget(2, QFormLayout::LabelRole, label_15);


        player3_info->addLayout(formLayout_2);

        verticalLayout = new QVBoxLayout();
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        picture3 = new QLabel(verticalLayoutWidget_3);
        picture3->setObjectName(QString::fromUtf8("picture3"));
        picture3->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/player3.jpg")));

        verticalLayout->addWidget(picture3);

        name3 = new QLabel(verticalLayoutWidget_3);
        name3->setObjectName(QString::fromUtf8("name3"));

        verticalLayout->addWidget(name3);

        radioButton_2 = new QRadioButton(verticalLayoutWidget_3);
        radioButton_2->setObjectName(QString::fromUtf8("radioButton_2"));
        radioButton_2->setEnabled(false);

        verticalLayout->addWidget(radioButton_2);


        player3_info->addLayout(verticalLayout);


        verticalLayout_2->addLayout(player3_info);

        player4_info = new QHBoxLayout();
        player4_info->setObjectName(QString::fromUtf8("player4_info"));
        formLayout = new QFormLayout();
        formLayout->setObjectName(QString::fromUtf8("formLayout"));
        label_2 = new QLabel(verticalLayoutWidget_3);
        label_2->setObjectName(QString::fromUtf8("label_2"));

        formLayout->setWidget(0, QFormLayout::LabelRole, label_2);

        label_4 = new QLabel(verticalLayoutWidget_3);
        label_4->setObjectName(QString::fromUtf8("label_4"));

        formLayout->setWidget(1, QFormLayout::LabelRole, label_4);

        label_5 = new QLabel(verticalLayoutWidget_3);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/wheat.png")));

        formLayout->setWidget(1, QFormLayout::FieldRole, label_5);

        label_6 = new QLabel(verticalLayoutWidget_3);
        label_6->setObjectName(QString::fromUtf8("label_6"));

        formLayout->setWidget(2, QFormLayout::LabelRole, label_6);

        label_7 = new QLabel(verticalLayoutWidget_3);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/stone.png")));

        formLayout->setWidget(2, QFormLayout::FieldRole, label_7);

        label_8 = new QLabel(verticalLayoutWidget_3);
        label_8->setObjectName(QString::fromUtf8("label_8"));

        formLayout->setWidget(3, QFormLayout::LabelRole, label_8);

        label_9 = new QLabel(verticalLayoutWidget_3);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/wood.png")));

        formLayout->setWidget(3, QFormLayout::FieldRole, label_9);

        label_10 = new QLabel(verticalLayoutWidget_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));

        formLayout->setWidget(4, QFormLayout::LabelRole, label_10);

        label_11 = new QLabel(verticalLayoutWidget_3);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/brick1.png")));

        formLayout->setWidget(4, QFormLayout::FieldRole, label_11);

        label_3 = new QLabel(verticalLayoutWidget_3);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/shaep.png")));

        formLayout->setWidget(0, QFormLayout::FieldRole, label_3);


        player4_info->addLayout(formLayout);

        player4 = new QVBoxLayout();
        player4->setObjectName(QString::fromUtf8("player4"));
        picture4 = new QLabel(verticalLayoutWidget_3);
        picture4->setObjectName(QString::fromUtf8("picture4"));
        picture4->setPixmap(QPixmap(QString::fromUtf8(":/prefix1/image/player1.jpg")));

        player4->addWidget(picture4);

        name4 = new QLabel(verticalLayoutWidget_3);
        name4->setObjectName(QString::fromUtf8("name4"));

        player4->addWidget(name4);

        radioButton = new QRadioButton(verticalLayoutWidget_3);
        radioButton->setObjectName(QString::fromUtf8("radioButton"));
        radioButton->setEnabled(false);

        player4->addWidget(radioButton);


        player4_info->addLayout(player4);


        verticalLayout_2->addLayout(player4_info);

        dice = new QPushButton(centralwidget);
        dice->setObjectName(QString::fromUtf8("dice"));
        dice->setGeometry(QRect(540, 530, 51, 51));
        QSizePolicy sizePolicy(QSizePolicy::Maximum, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(dice->sizePolicy().hasHeightForWidth());
        dice->setSizePolicy(sizePolicy);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/prefix1/image/dice1.png"), QSize(), QIcon::Normal, QIcon::Off);
        dice->setIcon(icon);
        dice->setIconSize(QSize(45, 45));
        robber = new QPushButton(centralwidget);
        robber->setObjectName(QString::fromUtf8("robber"));
        robber->setGeometry(QRect(360, 530, 51, 51));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/prefix1/image/robber.png"), QSize(), QIcon::Normal, QIcon::Off);
        robber->setIcon(icon1);
        robber->setIconSize(QSize(50, 50));
        end = new QPushButton(centralwidget);
        end->setObjectName(QString::fromUtf8("end"));
        end->setGeometry(QRect(420, 530, 51, 51));
        sizePolicy.setHeightForWidth(end->sizePolicy().hasHeightForWidth());
        end->setSizePolicy(sizePolicy);
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/prefix1/image/end2.png"), QSize(), QIcon::Normal, QIcon::Off);
        end->setIcon(icon2);
        end->setIconSize(QSize(45, 45));
        trade = new QPushButton(centralwidget);
        trade->setObjectName(QString::fromUtf8("trade"));
        trade->setGeometry(QRect(480, 530, 51, 51));
        sizePolicy.setHeightForWidth(trade->sizePolicy().hasHeightForWidth());
        trade->setSizePolicy(sizePolicy);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/prefix1/image/trade1.png"), QSize(), QIcon::Normal, QIcon::Off);
        trade->setIcon(icon3);
        trade->setIconSize(QSize(45, 45));
        developmentcard = new QPushButton(centralwidget);
        developmentcard->setObjectName(QString::fromUtf8("developmentcard"));
        developmentcard->setGeometry(QRect(600, 530, 51, 51));
        sizePolicy.setHeightForWidth(developmentcard->sizePolicy().hasHeightForWidth());
        developmentcard->setSizePolicy(sizePolicy);
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/prefix1/image/3338970_business tools_card_credit_atm_atm card_icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        developmentcard->setIcon(icon4);
        developmentcard->setIconSize(QSize(45, 45));
        t9 = new QPushButton(centralwidget);
        t9->setObjectName(QString::fromUtf8("t9"));
        t9->setGeometry(QRect(330, 220, 21, 21));
        t9->setFlat(true);
        t21 = new QPushButton(centralwidget);
        t21->setObjectName(QString::fromUtf8("t21"));
        t21->setGeometry(QRect(620, 180, 21, 21));
        t21->setFlat(true);
        t5 = new QPushButton(centralwidget);
        t5->setObjectName(QString::fromUtf8("t5"));
        t5->setGeometry(QRect(370, 170, 21, 21));
        t5->setFlat(true);
        t1 = new QPushButton(centralwidget);
        t1->setObjectName(QString::fromUtf8("t1"));
        t1->setGeometry(QRect(340, 130, 21, 21));
        t1->setFlat(true);
        t18 = new QPushButton(centralwidget);
        t18->setObjectName(QString::fromUtf8("t18"));
        t18->setGeometry(QRect(400, 320, 21, 21));
        t18->setFlat(true);
        t10 = new QPushButton(centralwidget);
        t10->setObjectName(QString::fromUtf8("t10"));
        t10->setGeometry(QRect(400, 220, 21, 21));
        t10->setFlat(true);
        t25 = new QPushButton(centralwidget);
        t25->setObjectName(QString::fromUtf8("t25"));
        t25->setGeometry(QRect(660, 320, 21, 21));
        t25->setFlat(true);
        t8 = new QPushButton(centralwidget);
        t8->setObjectName(QString::fromUtf8("t8"));
        t8->setGeometry(QRect(270, 220, 21, 21));
        t8->setFlat(true);
        t7 = new QPushButton(centralwidget);
        t7->setObjectName(QString::fromUtf8("t7"));
        t7->setGeometry(QRect(500, 170, 21, 21));
        t7->setFlat(true);
        t13 = new QPushButton(centralwidget);
        t13->setObjectName(QString::fromUtf8("t13"));
        t13->setGeometry(QRect(300, 270, 21, 21));
        t13->setFlat(true);
        t20 = new QPushButton(centralwidget);
        t20->setObjectName(QString::fromUtf8("t20"));
        t20->setGeometry(QRect(590, 130, 21, 21));
        t20->setFlat(true);
        t24 = new QPushButton(centralwidget);
        t24->setObjectName(QString::fromUtf8("t24"));
        t24->setGeometry(QRect(600, 320, 21, 21));
        t24->setFlat(true);
        t27 = new QPushButton(centralwidget);
        t27->setObjectName(QString::fromUtf8("t27"));
        t27->setGeometry(QRect(630, 370, 21, 21));
        t27->setFlat(true);
        t16 = new QPushButton(centralwidget);
        t16->setObjectName(QString::fromUtf8("t16"));
        t16->setGeometry(QRect(490, 270, 21, 21));
        t16->setFlat(true);
        t12 = new QPushButton(centralwidget);
        t12->setObjectName(QString::fromUtf8("t12"));
        t12->setGeometry(QRect(530, 220, 21, 21));
        t12->setFlat(true);
        t17 = new QPushButton(centralwidget);
        t17->setObjectName(QString::fromUtf8("t17"));
        t17->setGeometry(QRect(320, 320, 21, 21));
        t17->setFlat(true);
        t19 = new QPushButton(centralwidget);
        t19->setObjectName(QString::fromUtf8("t19"));
        t19->setGeometry(QRect(470, 320, 21, 21));
        t19->setFlat(true);
        t14 = new QPushButton(centralwidget);
        t14->setObjectName(QString::fromUtf8("t14"));
        t14->setGeometry(QRect(360, 270, 21, 21));
        t14->setFlat(true);
        t4 = new QPushButton(centralwidget);
        t4->setObjectName(QString::fromUtf8("t4"));
        t4->setGeometry(QRect(300, 170, 21, 21));
        t4->setFlat(true);
        t6 = new QPushButton(centralwidget);
        t6->setObjectName(QString::fromUtf8("t6"));
        t6->setGeometry(QRect(440, 170, 21, 21));
        t6->setFlat(true);
        t11 = new QPushButton(centralwidget);
        t11->setObjectName(QString::fromUtf8("t11"));
        t11->setGeometry(QRect(460, 220, 21, 21));
        t11->setFlat(true);
        t23 = new QPushButton(centralwidget);
        t23->setObjectName(QString::fromUtf8("t23"));
        t23->setGeometry(QRect(700, 270, 21, 21));
        t23->setFlat(true);
        t28 = new QPushButton(centralwidget);
        t28->setObjectName(QString::fromUtf8("t28"));
        t28->setGeometry(QRect(460, 430, 21, 21));
        t28->setFlat(true);
        t26 = new QPushButton(centralwidget);
        t26->setObjectName(QString::fromUtf8("t26"));
        t26->setGeometry(QRect(570, 370, 21, 21));
        t26->setFlat(true);
        t2 = new QPushButton(centralwidget);
        t2->setObjectName(QString::fromUtf8("t2"));
        t2->setGeometry(QRect(400, 130, 21, 21));
        t2->setFlat(true);
        t3 = new QPushButton(centralwidget);
        t3->setObjectName(QString::fromUtf8("t3"));
        t3->setGeometry(QRect(460, 130, 21, 21));
        t3->setFlat(true);
        t22 = new QPushButton(centralwidget);
        t22->setObjectName(QString::fromUtf8("t22"));
        t22->setGeometry(QRect(660, 220, 21, 21));
        t22->setFlat(true);
        t15 = new QPushButton(centralwidget);
        t15->setObjectName(QString::fromUtf8("t15"));
        t15->setGeometry(QRect(430, 270, 21, 21));
        t15->setFlat(true);
        b5 = new QPushButton(centralwidget);
        b5->setObjectName(QString::fromUtf8("b5"));
        b5->setGeometry(QRect(580, 250, 16, 16));
        b5->setFlat(true);
        b7 = new QPushButton(centralwidget);
        b7->setObjectName(QString::fromUtf8("b7"));
        b7->setGeometry(QRect(600, 270, 16, 16));
        b7->setFlat(true);
        b10 = new QPushButton(centralwidget);
        b10->setObjectName(QString::fromUtf8("b10"));
        b10->setGeometry(QRect(400, 380, 16, 16));
        b10->setFlat(true);
        b1 = new QPushButton(centralwidget);
        b1->setObjectName(QString::fromUtf8("b1"));
        b1->setGeometry(QRect(520, 110, 16, 16));
        b1->setFlat(true);
        b3 = new QPushButton(centralwidget);
        b3->setObjectName(QString::fromUtf8("b3"));
        b3->setGeometry(QRect(550, 150, 16, 16));
        b3->setFlat(true);
        b4 = new QPushButton(centralwidget);
        b4->setObjectName(QString::fromUtf8("b4"));
        b4->setGeometry(QRect(580, 200, 16, 16));
        b4->setFlat(true);
        b13 = new QPushButton(centralwidget);
        b13->setObjectName(QString::fromUtf8("b13"));
        b13->setGeometry(QRect(520, 400, 16, 16));
        b13->setFlat(true);
        b11 = new QPushButton(centralwidget);
        b11->setObjectName(QString::fromUtf8("b11"));
        b11->setGeometry(QRect(470, 380, 16, 16));
        b11->setFlat(true);
        b6 = new QPushButton(centralwidget);
        b6->setObjectName(QString::fromUtf8("b6"));
        b6->setGeometry(QRect(610, 250, 16, 16));
        b6->setFlat(true);
        b8 = new QPushButton(centralwidget);
        b8->setObjectName(QString::fromUtf8("b8"));
        b8->setGeometry(QRect(550, 300, 16, 16));
        b8->setFlat(true);
        b2 = new QPushButton(centralwidget);
        b2->setObjectName(QString::fromUtf8("b2"));
        b2->setGeometry(QRect(540, 110, 16, 16));
        b2->setFlat(true);
        b12 = new QPushButton(centralwidget);
        b12->setObjectName(QString::fromUtf8("b12"));
        b12->setGeometry(QRect(410, 400, 16, 16));
        b12->setFlat(true);
        b9 = new QPushButton(centralwidget);
        b9->setObjectName(QString::fromUtf8("b9"));
        b9->setGeometry(QRect(520, 350, 16, 16));
        b9->setFlat(true);
        e1 = new QPushButton(centralwidget);
        e1->setObjectName(QString::fromUtf8("e1"));
        e1->setGeometry(QRect(330, 110, 16, 16));
        e1->setFlat(true);
        e2 = new QPushButton(centralwidget);
        e2->setObjectName(QString::fromUtf8("e2"));
        e2->setGeometry(QRect(360, 110, 16, 16));
        e2->setFlat(true);
        e3 = new QPushButton(centralwidget);
        e3->setObjectName(QString::fromUtf8("e3"));
        e3->setGeometry(QRect(390, 110, 16, 16));
        e3->setFlat(true);
        e4 = new QPushButton(centralwidget);
        e4->setObjectName(QString::fromUtf8("e4"));
        e4->setGeometry(QRect(420, 110, 16, 16));
        e4->setFlat(true);
        e5 = new QPushButton(centralwidget);
        e5->setObjectName(QString::fromUtf8("e5"));
        e5->setGeometry(QRect(450, 110, 16, 16));
        e5->setFlat(true);
        e6 = new QPushButton(centralwidget);
        e6->setObjectName(QString::fromUtf8("e6"));
        e6->setGeometry(QRect(490, 110, 16, 16));
        e6->setFlat(true);
        e7 = new QPushButton(centralwidget);
        e7->setObjectName(QString::fromUtf8("e7"));
        e7->setGeometry(QRect(310, 130, 16, 16));
        e7->setFlat(true);
        e8 = new QPushButton(centralwidget);
        e8->setObjectName(QString::fromUtf8("e8"));
        e8->setGeometry(QRect(370, 130, 16, 16));
        e8->setFlat(true);
        e9 = new QPushButton(centralwidget);
        e9->setObjectName(QString::fromUtf8("e9"));
        e9->setGeometry(QRect(440, 130, 16, 16));
        e9->setFlat(true);
        e10 = new QPushButton(centralwidget);
        e10->setObjectName(QString::fromUtf8("e10"));
        e10->setGeometry(QRect(500, 130, 16, 16));
        e10->setFlat(true);
        e11 = new QPushButton(centralwidget);
        e11->setObjectName(QString::fromUtf8("e11"));
        e11->setGeometry(QRect(290, 150, 16, 16));
        e11->setFlat(true);
        e12 = new QPushButton(centralwidget);
        e12->setObjectName(QString::fromUtf8("e12"));
        e12->setGeometry(QRect(330, 150, 16, 16));
        e12->setFlat(true);
        e13 = new QPushButton(centralwidget);
        e13->setObjectName(QString::fromUtf8("e13"));
        e13->setGeometry(QRect(360, 150, 16, 16));
        e13->setFlat(true);
        e14 = new QPushButton(centralwidget);
        e14->setObjectName(QString::fromUtf8("e14"));
        e14->setGeometry(QRect(390, 150, 16, 16));
        e14->setFlat(true);
        e15 = new QPushButton(centralwidget);
        e15->setObjectName(QString::fromUtf8("e15"));
        e15->setGeometry(QRect(420, 150, 16, 16));
        e15->setFlat(true);
        e16 = new QPushButton(centralwidget);
        e16->setObjectName(QString::fromUtf8("e16"));
        e16->setGeometry(QRect(450, 150, 16, 16));
        e16->setFlat(true);
        e17 = new QPushButton(centralwidget);
        e17->setObjectName(QString::fromUtf8("e17"));
        e17->setGeometry(QRect(480, 150, 16, 16));
        e17->setFlat(true);
        e18 = new QPushButton(centralwidget);
        e18->setObjectName(QString::fromUtf8("e18"));
        e18->setGeometry(QRect(520, 150, 16, 16));
        e18->setFlat(true);
        e19 = new QPushButton(centralwidget);
        e19->setObjectName(QString::fromUtf8("e19"));
        e19->setGeometry(QRect(280, 180, 16, 16));
        e19->setFlat(true);
        e20 = new QPushButton(centralwidget);
        e20->setObjectName(QString::fromUtf8("e20"));
        e20->setGeometry(QRect(340, 180, 16, 16));
        e20->setFlat(true);
        e21 = new QPushButton(centralwidget);
        e21->setObjectName(QString::fromUtf8("e21"));
        e21->setGeometry(QRect(400, 180, 16, 16));
        e21->setFlat(true);
        e22 = new QPushButton(centralwidget);
        e22->setObjectName(QString::fromUtf8("e22"));
        e22->setGeometry(QRect(470, 180, 16, 16));
        e22->setFlat(true);
        e23 = new QPushButton(centralwidget);
        e23->setObjectName(QString::fromUtf8("e23"));
        e23->setGeometry(QRect(530, 180, 16, 16));
        e23->setFlat(true);
        e24 = new QPushButton(centralwidget);
        e24->setObjectName(QString::fromUtf8("e24"));
        e24->setGeometry(QRect(260, 200, 16, 16));
        e24->setFlat(true);
        e25 = new QPushButton(centralwidget);
        e25->setObjectName(QString::fromUtf8("e25"));
        e25->setGeometry(QRect(290, 200, 16, 16));
        e25->setFlat(true);
        e26 = new QPushButton(centralwidget);
        e26->setObjectName(QString::fromUtf8("e26"));
        e26->setGeometry(QRect(330, 200, 16, 16));
        e26->setFlat(true);
        e27 = new QPushButton(centralwidget);
        e27->setObjectName(QString::fromUtf8("e27"));
        e27->setGeometry(QRect(360, 200, 16, 16));
        e27->setFlat(true);
        e28 = new QPushButton(centralwidget);
        e28->setObjectName(QString::fromUtf8("e28"));
        e28->setGeometry(QRect(390, 200, 16, 16));
        e28->setFlat(true);
        e29 = new QPushButton(centralwidget);
        e29->setObjectName(QString::fromUtf8("e29"));
        e29->setGeometry(QRect(420, 200, 16, 16));
        e29->setFlat(true);
        e30 = new QPushButton(centralwidget);
        e30->setObjectName(QString::fromUtf8("e30"));
        e30->setGeometry(QRect(450, 200, 16, 16));
        e30->setFlat(true);
        e31 = new QPushButton(centralwidget);
        e31->setObjectName(QString::fromUtf8("e31"));
        e31->setGeometry(QRect(490, 200, 16, 16));
        e31->setFlat(true);
        e32 = new QPushButton(centralwidget);
        e32->setObjectName(QString::fromUtf8("e32"));
        e32->setGeometry(QRect(520, 200, 16, 16));
        e32->setFlat(true);
        e33 = new QPushButton(centralwidget);
        e33->setObjectName(QString::fromUtf8("e33"));
        e33->setGeometry(QRect(550, 200, 16, 16));
        e33->setFlat(true);
        e34 = new QPushButton(centralwidget);
        e34->setObjectName(QString::fromUtf8("e34"));
        e34->setGeometry(QRect(240, 220, 16, 16));
        e34->setFlat(true);
        e35 = new QPushButton(centralwidget);
        e35->setObjectName(QString::fromUtf8("e35"));
        e35->setGeometry(QRect(310, 220, 16, 16));
        e35->setFlat(true);
        e36 = new QPushButton(centralwidget);
        e36->setObjectName(QString::fromUtf8("e36"));
        e36->setGeometry(QRect(370, 220, 16, 16));
        e36->setFlat(true);
        e37 = new QPushButton(centralwidget);
        e37->setObjectName(QString::fromUtf8("e37"));
        e37->setGeometry(QRect(440, 220, 16, 16));
        e37->setFlat(true);
        e38 = new QPushButton(centralwidget);
        e38->setObjectName(QString::fromUtf8("e38"));
        e38->setGeometry(QRect(500, 220, 16, 16));
        e38->setFlat(true);
        e39 = new QPushButton(centralwidget);
        e39->setObjectName(QString::fromUtf8("e39"));
        e39->setGeometry(QRect(560, 220, 16, 16));
        e39->setFlat(true);
        e40 = new QPushButton(centralwidget);
        e40->setObjectName(QString::fromUtf8("e40"));
        e40->setGeometry(QRect(250, 250, 16, 16));
        e40->setFlat(true);
        e41 = new QPushButton(centralwidget);
        e41->setObjectName(QString::fromUtf8("e41"));
        e41->setGeometry(QRect(290, 250, 16, 16));
        e41->setFlat(true);
        e42 = new QPushButton(centralwidget);
        e42->setObjectName(QString::fromUtf8("e42"));
        e42->setGeometry(QRect(320, 250, 16, 16));
        e42->setFlat(true);
        e43 = new QPushButton(centralwidget);
        e43->setObjectName(QString::fromUtf8("e43"));
        e43->setGeometry(QRect(360, 250, 16, 16));
        e43->setFlat(true);
        e44 = new QPushButton(centralwidget);
        e44->setObjectName(QString::fromUtf8("e44"));
        e44->setGeometry(QRect(390, 250, 16, 16));
        e44->setFlat(true);
        e45 = new QPushButton(centralwidget);
        e45->setObjectName(QString::fromUtf8("e45"));
        e45->setGeometry(QRect(420, 250, 16, 16));
        e45->setFlat(true);
        e46 = new QPushButton(centralwidget);
        e46->setObjectName(QString::fromUtf8("e46"));
        e46->setGeometry(QRect(450, 250, 16, 16));
        e46->setFlat(true);
        e47 = new QPushButton(centralwidget);
        e47->setObjectName(QString::fromUtf8("e47"));
        e47->setGeometry(QRect(480, 250, 16, 16));
        e47->setFlat(true);
        e48 = new QPushButton(centralwidget);
        e48->setObjectName(QString::fromUtf8("e48"));
        e48->setGeometry(QRect(520, 250, 16, 16));
        e48->setFlat(true);
        e49 = new QPushButton(centralwidget);
        e49->setObjectName(QString::fromUtf8("e49"));
        e49->setGeometry(QRect(550, 250, 16, 16));
        e49->setFlat(true);
        e50 = new QPushButton(centralwidget);
        e50->setObjectName(QString::fromUtf8("e50"));
        e50->setGeometry(QRect(270, 270, 16, 16));
        e50->setFlat(true);
        e51 = new QPushButton(centralwidget);
        e51->setObjectName(QString::fromUtf8("e51"));
        e51->setGeometry(QRect(330, 270, 16, 16));
        e51->setFlat(true);
        e52 = new QPushButton(centralwidget);
        e52->setObjectName(QString::fromUtf8("e52"));
        e52->setGeometry(QRect(400, 270, 16, 16));
        e52->setFlat(true);
        e53 = new QPushButton(centralwidget);
        e53->setObjectName(QString::fromUtf8("e53"));
        e53->setGeometry(QRect(460, 270, 16, 16));
        e53->setFlat(true);
        e54 = new QPushButton(centralwidget);
        e54->setObjectName(QString::fromUtf8("e54"));
        e54->setGeometry(QRect(530, 270, 16, 16));
        e54->setFlat(true);
        e55 = new QPushButton(centralwidget);
        e55->setObjectName(QString::fromUtf8("e55"));
        e55->setGeometry(QRect(290, 300, 16, 16));
        e55->setFlat(true);
        e56 = new QPushButton(centralwidget);
        e56->setObjectName(QString::fromUtf8("e56"));
        e56->setGeometry(QRect(320, 300, 16, 16));
        e56->setFlat(true);
        e57 = new QPushButton(centralwidget);
        e57->setObjectName(QString::fromUtf8("e57"));
        e57->setGeometry(QRect(350, 300, 16, 16));
        e57->setFlat(true);
        e58 = new QPushButton(centralwidget);
        e58->setObjectName(QString::fromUtf8("e58"));
        e58->setGeometry(QRect(390, 300, 16, 16));
        e58->setFlat(true);
        e59 = new QPushButton(centralwidget);
        e59->setObjectName(QString::fromUtf8("e59"));
        e59->setGeometry(QRect(420, 300, 16, 16));
        e59->setFlat(true);
        e60 = new QPushButton(centralwidget);
        e60->setObjectName(QString::fromUtf8("e60"));
        e60->setGeometry(QRect(450, 300, 16, 16));
        e60->setFlat(true);
        e61 = new QPushButton(centralwidget);
        e61->setObjectName(QString::fromUtf8("e61"));
        e61->setGeometry(QRect(480, 300, 16, 16));
        e61->setFlat(true);
        e62 = new QPushButton(centralwidget);
        e62->setObjectName(QString::fromUtf8("e62"));
        e62->setGeometry(QRect(520, 300, 16, 16));
        e62->setFlat(true);
        e63 = new QPushButton(centralwidget);
        e63->setObjectName(QString::fromUtf8("e63"));
        e63->setGeometry(QRect(300, 320, 16, 16));
        e63->setFlat(true);
        e64 = new QPushButton(centralwidget);
        e64->setObjectName(QString::fromUtf8("e64"));
        e64->setGeometry(QRect(370, 320, 16, 16));
        e64->setFlat(true);
        e65 = new QPushButton(centralwidget);
        e65->setObjectName(QString::fromUtf8("e65"));
        e65->setGeometry(QRect(430, 330, 16, 16));
        e65->setFlat(true);
        e66 = new QPushButton(centralwidget);
        e66->setObjectName(QString::fromUtf8("e66"));
        e66->setGeometry(QRect(500, 320, 16, 16));
        e66->setFlat(true);
        e67 = new QPushButton(centralwidget);
        e67->setObjectName(QString::fromUtf8("e67"));
        e67->setGeometry(QRect(320, 350, 16, 16));
        e67->setFlat(true);
        e68 = new QPushButton(centralwidget);
        e68->setObjectName(QString::fromUtf8("e68"));
        e68->setGeometry(QRect(350, 350, 16, 16));
        e68->setFlat(true);
        e69 = new QPushButton(centralwidget);
        e69->setObjectName(QString::fromUtf8("e69"));
        e69->setGeometry(QRect(380, 350, 16, 16));
        e69->setFlat(true);
        e70 = new QPushButton(centralwidget);
        e70->setObjectName(QString::fromUtf8("e70"));
        e70->setGeometry(QRect(420, 350, 16, 16));
        e70->setFlat(true);
        e71 = new QPushButton(centralwidget);
        e71->setObjectName(QString::fromUtf8("e71"));
        e71->setGeometry(QRect(450, 350, 16, 16));
        e71->setFlat(true);
        e72 = new QPushButton(centralwidget);
        e72->setObjectName(QString::fromUtf8("e72"));
        e72->setGeometry(QRect(480, 350, 16, 16));
        e72->setFlat(true);
        e73 = new QPushButton(centralwidget);
        e73->setObjectName(QString::fromUtf8("e73"));
        e73->setGeometry(QRect(580, 110, 16, 16));
        e73->setFlat(true);
        e74 = new QPushButton(centralwidget);
        e74->setObjectName(QString::fromUtf8("e74"));
        e74->setGeometry(QRect(610, 110, 16, 16));
        e74->setFlat(true);
        e75 = new QPushButton(centralwidget);
        e75->setObjectName(QString::fromUtf8("e75"));
        e75->setGeometry(QRect(560, 130, 16, 16));
        e75->setFlat(true);
        e76 = new QPushButton(centralwidget);
        e76->setObjectName(QString::fromUtf8("e76"));
        e76->setGeometry(QRect(630, 130, 16, 16));
        e76->setFlat(true);
        e77 = new QPushButton(centralwidget);
        e77->setObjectName(QString::fromUtf8("e77"));
        e77->setGeometry(QRect(580, 160, 16, 16));
        e77->setFlat(true);
        e78 = new QPushButton(centralwidget);
        e78->setObjectName(QString::fromUtf8("e78"));
        e78->setGeometry(QRect(610, 160, 16, 16));
        e78->setFlat(true);
        e79 = new QPushButton(centralwidget);
        e79->setObjectName(QString::fromUtf8("e79"));
        e79->setGeometry(QRect(640, 160, 16, 16));
        e79->setFlat(true);
        e80 = new QPushButton(centralwidget);
        e80->setObjectName(QString::fromUtf8("e80"));
        e80->setGeometry(QRect(590, 180, 16, 16));
        e80->setFlat(true);
        e81 = new QPushButton(centralwidget);
        e81->setObjectName(QString::fromUtf8("e81"));
        e81->setGeometry(QRect(660, 180, 16, 16));
        e81->setFlat(true);
        e82 = new QPushButton(centralwidget);
        e82->setObjectName(QString::fromUtf8("e82"));
        e82->setGeometry(QRect(610, 200, 16, 16));
        e82->setFlat(true);
        e83 = new QPushButton(centralwidget);
        e83->setObjectName(QString::fromUtf8("e83"));
        e83->setGeometry(QRect(640, 200, 16, 16));
        e83->setFlat(true);
        e84 = new QPushButton(centralwidget);
        e84->setObjectName(QString::fromUtf8("e84"));
        e84->setGeometry(QRect(680, 200, 16, 16));
        e84->setFlat(true);
        e85 = new QPushButton(centralwidget);
        e85->setObjectName(QString::fromUtf8("e85"));
        e85->setGeometry(QRect(630, 230, 16, 16));
        e85->setFlat(true);
        e86 = new QPushButton(centralwidget);
        e86->setObjectName(QString::fromUtf8("e86"));
        e86->setGeometry(QRect(700, 230, 16, 16));
        e86->setFlat(true);
        e87 = new QPushButton(centralwidget);
        e87->setObjectName(QString::fromUtf8("e87"));
        e87->setGeometry(QRect(650, 250, 16, 16));
        e87->setFlat(true);
        e88 = new QPushButton(centralwidget);
        e88->setObjectName(QString::fromUtf8("e88"));
        e88->setGeometry(QRect(680, 250, 16, 16));
        e88->setFlat(true);
        e89 = new QPushButton(centralwidget);
        e89->setObjectName(QString::fromUtf8("e89"));
        e89->setGeometry(QRect(710, 250, 16, 16));
        e89->setFlat(true);
        e90 = new QPushButton(centralwidget);
        e90->setObjectName(QString::fromUtf8("e90"));
        e90->setGeometry(QRect(660, 280, 16, 16));
        e90->setFlat(true);
        e91 = new QPushButton(centralwidget);
        e91->setObjectName(QString::fromUtf8("e91"));
        e91->setGeometry(QRect(730, 280, 16, 16));
        e91->setFlat(true);
        e92 = new QPushButton(centralwidget);
        e92->setObjectName(QString::fromUtf8("e92"));
        e92->setGeometry(QRect(580, 300, 16, 16));
        e92->setFlat(true);
        e93 = new QPushButton(centralwidget);
        e93->setObjectName(QString::fromUtf8("e93"));
        e93->setGeometry(QRect(610, 300, 16, 16));
        e93->setFlat(true);
        e94 = new QPushButton(centralwidget);
        e94->setObjectName(QString::fromUtf8("e94"));
        e94->setGeometry(QRect(650, 300, 16, 16));
        e94->setFlat(true);
        e95 = new QPushButton(centralwidget);
        e95->setObjectName(QString::fromUtf8("e95"));
        e95->setGeometry(QRect(680, 300, 16, 16));
        e95->setFlat(true);
        e96 = new QPushButton(centralwidget);
        e96->setObjectName(QString::fromUtf8("e96"));
        e96->setGeometry(QRect(720, 300, 16, 16));
        e96->setFlat(true);
        e97 = new QPushButton(centralwidget);
        e97->setObjectName(QString::fromUtf8("e97"));
        e97->setGeometry(QRect(570, 330, 16, 16));
        e97->setFlat(true);
        e98 = new QPushButton(centralwidget);
        e98->setObjectName(QString::fromUtf8("e98"));
        e98->setGeometry(QRect(630, 320, 16, 16));
        e98->setFlat(true);
        e99 = new QPushButton(centralwidget);
        e99->setObjectName(QString::fromUtf8("e99"));
        e99->setGeometry(QRect(700, 320, 16, 16));
        e99->setFlat(true);
        e100 = new QPushButton(centralwidget);
        e100->setObjectName(QString::fromUtf8("e100"));
        e100->setGeometry(QRect(550, 350, 16, 16));
        e100->setFlat(true);
        e101 = new QPushButton(centralwidget);
        e101->setObjectName(QString::fromUtf8("e101"));
        e101->setGeometry(QRect(580, 350, 16, 16));
        e101->setFlat(true);
        e102 = new QPushButton(centralwidget);
        e102->setObjectName(QString::fromUtf8("e102"));
        e102->setGeometry(QRect(620, 350, 16, 16));
        e102->setFlat(true);
        e103 = new QPushButton(centralwidget);
        e103->setObjectName(QString::fromUtf8("e103"));
        e103->setGeometry(QRect(650, 350, 16, 16));
        e103->setFlat(true);
        e104 = new QPushButton(centralwidget);
        e104->setObjectName(QString::fromUtf8("e104"));
        e104->setGeometry(QRect(680, 350, 16, 16));
        e104->setFlat(true);
        e105 = new QPushButton(centralwidget);
        e105->setObjectName(QString::fromUtf8("e105"));
        e105->setGeometry(QRect(530, 380, 16, 16));
        e105->setFlat(true);
        e106 = new QPushButton(centralwidget);
        e106->setObjectName(QString::fromUtf8("e106"));
        e106->setGeometry(QRect(600, 380, 16, 16));
        e106->setFlat(true);
        e107 = new QPushButton(centralwidget);
        e107->setObjectName(QString::fromUtf8("e107"));
        e107->setGeometry(QRect(670, 380, 16, 16));
        e107->setFlat(true);
        e108 = new QPushButton(centralwidget);
        e108->setObjectName(QString::fromUtf8("e108"));
        e108->setGeometry(QRect(550, 400, 16, 16));
        e108->setFlat(true);
        e109 = new QPushButton(centralwidget);
        e109->setObjectName(QString::fromUtf8("e109"));
        e109->setGeometry(QRect(590, 400, 16, 16));
        e109->setFlat(true);
        e110 = new QPushButton(centralwidget);
        e110->setObjectName(QString::fromUtf8("e110"));
        e110->setGeometry(QRect(620, 400, 16, 16));
        e110->setFlat(true);
        e111 = new QPushButton(centralwidget);
        e111->setObjectName(QString::fromUtf8("e111"));
        e111->setGeometry(QRect(660, 400, 16, 16));
        e111->setFlat(true);
        e112 = new QPushButton(centralwidget);
        e112->setObjectName(QString::fromUtf8("e112"));
        e112->setGeometry(QRect(450, 400, 16, 16));
        e112->setFlat(true);
        e113 = new QPushButton(centralwidget);
        e113->setObjectName(QString::fromUtf8("e113"));
        e113->setGeometry(QRect(480, 400, 16, 16));
        e113->setFlat(true);
        e114 = new QPushButton(centralwidget);
        e114->setObjectName(QString::fromUtf8("e114"));
        e114->setGeometry(QRect(430, 430, 16, 16));
        e114->setFlat(true);
        e115 = new QPushButton(centralwidget);
        e115->setObjectName(QString::fromUtf8("e115"));
        e115->setGeometry(QRect(500, 430, 16, 16));
        e115->setFlat(true);
        e116 = new QPushButton(centralwidget);
        e116->setObjectName(QString::fromUtf8("e116"));
        e116->setGeometry(QRect(450, 460, 16, 16));
        e116->setFlat(true);
        e117 = new QPushButton(centralwidget);
        e117->setObjectName(QString::fromUtf8("e117"));
        e117->setGeometry(QRect(480, 460, 16, 16));
        e117->setFlat(true);
        playground->setCentralWidget(centralwidget);
        menubar = new QMenuBar(playground);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1010, 26));
        playground->setMenuBar(menubar);
        statusbar = new QStatusBar(playground);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        playground->setStatusBar(statusbar);

        retranslateUi(playground);

        QMetaObject::connectSlotsByName(playground);
    } // setupUi

    void retranslateUi(QMainWindow *playground)
    {
        playground->setWindowTitle(QCoreApplication::translate("playground", "MainWindow", nullptr));
        background->setText(QString());
        v1->setText(QCoreApplication::translate("playground", "1", nullptr));
        v2->setText(QCoreApplication::translate("playground", "2", nullptr));
        v3->setText(QCoreApplication::translate("playground", "3", nullptr));
        v4->setText(QCoreApplication::translate("playground", "4", nullptr));
        v5->setText(QCoreApplication::translate("playground", "5", nullptr));
        v6->setText(QCoreApplication::translate("playground", "6", nullptr));
        v17->setText(QCoreApplication::translate("playground", "17", nullptr));
        v28->setText(QCoreApplication::translate("playground", "28", nullptr));
        v39->setText(QCoreApplication::translate("playground", "39", nullptr));
        v50->setText(QCoreApplication::translate("playground", "50", nullptr));
        v61->setText(QCoreApplication::translate("playground", "61", nullptr));
        v72->setText(QCoreApplication::translate("playground", "72", nullptr));
        v84->setText(QCoreApplication::translate("playground", "84", nullptr));
        v92->setText(QCoreApplication::translate("playground", "92", nullptr));
        v7->setText(QCoreApplication::translate("playground", "7", nullptr));
        v8->setText(QCoreApplication::translate("playground", "8", nullptr));
        v9->setText(QCoreApplication::translate("playground", "9", nullptr));
        v10->setText(QCoreApplication::translate("playground", "10", nullptr));
        v11->setText(QCoreApplication::translate("playground", "11", nullptr));
        v12->setText(QCoreApplication::translate("playground", "12", nullptr));
        v13->setText(QCoreApplication::translate("playground", "13", nullptr));
        v14->setText(QCoreApplication::translate("playground", "14", nullptr));
        v15->setText(QCoreApplication::translate("playground", "15", nullptr));
        v16->setText(QCoreApplication::translate("playground", "16", nullptr));
        v18->setText(QCoreApplication::translate("playground", "18", nullptr));
        v19->setText(QCoreApplication::translate("playground", "19", nullptr));
        v20->setText(QCoreApplication::translate("playground", "20", nullptr));
        v21->setText(QCoreApplication::translate("playground", "21", nullptr));
        v22->setText(QCoreApplication::translate("playground", "22", nullptr));
        v23->setText(QCoreApplication::translate("playground", "23", nullptr));
        v24->setText(QCoreApplication::translate("playground", "24", nullptr));
        v25->setText(QCoreApplication::translate("playground", "25", nullptr));
        v26->setText(QCoreApplication::translate("playground", "26", nullptr));
        v27->setText(QCoreApplication::translate("playground", "27", nullptr));
        v29->setText(QCoreApplication::translate("playground", "29", nullptr));
        v30->setText(QCoreApplication::translate("playground", "30", nullptr));
        v31->setText(QCoreApplication::translate("playground", "31", nullptr));
        v32->setText(QCoreApplication::translate("playground", "32", nullptr));
        v33->setText(QCoreApplication::translate("playground", "33", nullptr));
        v34->setText(QCoreApplication::translate("playground", "34", nullptr));
        v35->setText(QCoreApplication::translate("playground", "35", nullptr));
        v36->setText(QCoreApplication::translate("playground", "36", nullptr));
        v37->setText(QCoreApplication::translate("playground", "37", nullptr));
        v38->setText(QCoreApplication::translate("playground", "38", nullptr));
        v40->setText(QCoreApplication::translate("playground", "40", nullptr));
        v41->setText(QCoreApplication::translate("playground", "41", nullptr));
        v42->setText(QCoreApplication::translate("playground", "42", nullptr));
        v43->setText(QCoreApplication::translate("playground", "43", nullptr));
        v44->setText(QCoreApplication::translate("playground", "44", nullptr));
        v45->setText(QCoreApplication::translate("playground", "45", nullptr));
        v46->setText(QCoreApplication::translate("playground", "46", nullptr));
        v47->setText(QCoreApplication::translate("playground", "47", nullptr));
        v48->setText(QCoreApplication::translate("playground", "48", nullptr));
        v49->setText(QCoreApplication::translate("playground", "49", nullptr));
        v51->setText(QCoreApplication::translate("playground", "51", nullptr));
        v52->setText(QCoreApplication::translate("playground", "52", nullptr));
        v53->setText(QCoreApplication::translate("playground", "53", nullptr));
        v54->setText(QCoreApplication::translate("playground", "54", nullptr));
        v55->setText(QCoreApplication::translate("playground", "55", nullptr));
        v56->setText(QCoreApplication::translate("playground", "56", nullptr));
        v57->setText(QCoreApplication::translate("playground", "57", nullptr));
        v58->setText(QCoreApplication::translate("playground", "58", nullptr));
        v59->setText(QCoreApplication::translate("playground", "59", nullptr));
        v60->setText(QCoreApplication::translate("playground", "60", nullptr));
        v62->setText(QCoreApplication::translate("playground", "62", nullptr));
        v63->setText(QCoreApplication::translate("playground", "63", nullptr));
        v64->setText(QCoreApplication::translate("playground", "64", nullptr));
        v65->setText(QCoreApplication::translate("playground", "65", nullptr));
        v66->setText(QCoreApplication::translate("playground", "66", nullptr));
        v67->setText(QCoreApplication::translate("playground", "67", nullptr));
        v68->setText(QCoreApplication::translate("playground", "68", nullptr));
        v69->setText(QCoreApplication::translate("playground", "69", nullptr));
        v70->setText(QCoreApplication::translate("playground", "70", nullptr));
        v71->setText(QCoreApplication::translate("playground", "71", nullptr));
        v73->setText(QCoreApplication::translate("playground", "73", nullptr));
        v74->setText(QCoreApplication::translate("playground", "74", nullptr));
        v75->setText(QCoreApplication::translate("playground", "75", nullptr));
        v76->setText(QCoreApplication::translate("playground", "76", nullptr));
        v77->setText(QCoreApplication::translate("playground", "77", nullptr));
        v78->setText(QCoreApplication::translate("playground", "78", nullptr));
        v79->setText(QCoreApplication::translate("playground", "79", nullptr));
        v80->setText(QCoreApplication::translate("playground", "80", nullptr));
        v81->setText(QCoreApplication::translate("playground", "81", nullptr));
        v82->setText(QCoreApplication::translate("playground", "82", nullptr));
        v83->setText(QCoreApplication::translate("playground", "83", nullptr));
        v85->setText(QCoreApplication::translate("playground", "85", nullptr));
        v86->setText(QCoreApplication::translate("playground", "86", nullptr));
        v87->setText(QCoreApplication::translate("playground", "87", nullptr));
        v88->setText(QCoreApplication::translate("playground", "88", nullptr));
        v89->setText(QCoreApplication::translate("playground", "89", nullptr));
        v90->setText(QCoreApplication::translate("playground", "90", nullptr));
        v91->setText(QCoreApplication::translate("playground", "91", nullptr));
        guide->setText(QString());
        label_22->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_30->setText(QString());
        label_23->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_24->setText(QString());
        label_31->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_25->setText(QString());
        label_26->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_27->setText(QString());
        label_28->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_29->setText(QString());
        picture1->setText(QString());
        name1->setText(QString());
        radioButton_3->setText(QString());
        label_32->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_33->setText(QString());
        label_34->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_35->setText(QString());
        label_36->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_37->setText(QString());
        label_38->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_39->setText(QString());
        label_40->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_41->setText(QString());
        picture2->setText(QString());
        name2->setText(QString());
        radioButton_4->setText(QString());
        label_43->setText(QCoreApplication::translate("playground", "Select the building you want :", nullptr));
        ok->setText(QCoreApplication::translate("playground", "OK", nullptr));
        label_12->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_13->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_14->setText(QString());
        label_16->setText(QString());
        label_17->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_18->setText(QString());
        label_19->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_20->setText(QString());
        label_21->setText(QString());
        label_15->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        picture3->setText(QString());
        name3->setText(QString());
        radioButton_2->setText(QString());
        label_2->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_4->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_5->setText(QString());
        label_6->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_7->setText(QString());
        label_8->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_9->setText(QString());
        label_10->setText(QCoreApplication::translate("playground", "TextLabel", nullptr));
        label_11->setText(QString());
        label_3->setText(QString());
        picture4->setText(QString());
        name4->setText(QString());
        radioButton->setText(QString());
        dice->setText(QString());
        robber->setText(QString());
        end->setText(QString());
        trade->setText(QString());
        developmentcard->setText(QString());
        t9->setText(QString());
        t21->setText(QString());
        t5->setText(QString());
        t1->setText(QString());
        t18->setText(QString());
        t10->setText(QString());
        t25->setText(QString());
        t8->setText(QString());
        t7->setText(QString());
        t13->setText(QString());
        t20->setText(QString());
        t24->setText(QString());
        t27->setText(QString());
        t16->setText(QString());
        t12->setText(QString());
        t17->setText(QString());
        t19->setText(QString());
        t14->setText(QString());
        t4->setText(QString());
        t6->setText(QString());
        t11->setText(QString());
        t23->setText(QString());
        t28->setText(QString());
        t26->setText(QString());
        t2->setText(QString());
        t3->setText(QString());
        t22->setText(QString());
        t15->setText(QString());
        b5->setText(QString());
        b7->setText(QString());
        b10->setText(QString());
        b1->setText(QString());
        b3->setText(QString());
        b4->setText(QString());
        b13->setText(QString());
        b11->setText(QString());
        b6->setText(QString());
        b8->setText(QString());
        b2->setText(QString());
        b12->setText(QString());
        b9->setText(QString());
        e1->setText(QString());
        e2->setText(QString());
        e3->setText(QString());
        e4->setText(QString());
        e5->setText(QString());
        e6->setText(QString());
        e7->setText(QString());
        e8->setText(QString());
        e9->setText(QString());
        e10->setText(QString());
        e11->setText(QString());
        e12->setText(QString());
        e13->setText(QString());
        e14->setText(QString());
        e15->setText(QString());
        e16->setText(QString());
        e17->setText(QString());
        e18->setText(QString());
        e19->setText(QString());
        e20->setText(QString());
        e21->setText(QString());
        e22->setText(QString());
        e23->setText(QString());
        e24->setText(QString());
        e25->setText(QString());
        e26->setText(QString());
        e27->setText(QString());
        e28->setText(QString());
        e29->setText(QString());
        e30->setText(QString());
        e31->setText(QString());
        e32->setText(QString());
        e33->setText(QString());
        e34->setText(QString());
        e35->setText(QString());
        e36->setText(QString());
        e37->setText(QString());
        e38->setText(QString());
        e39->setText(QString());
        e40->setText(QString());
        e41->setText(QString());
        e42->setText(QString());
        e43->setText(QString());
        e44->setText(QString());
        e45->setText(QString());
        e46->setText(QString());
        e47->setText(QString());
        e48->setText(QString());
        e49->setText(QString());
        e50->setText(QString());
        e51->setText(QString());
        e52->setText(QString());
        e53->setText(QString());
        e54->setText(QString());
        e55->setText(QString());
        e56->setText(QString());
        e57->setText(QString());
        e58->setText(QString());
        e59->setText(QString());
        e60->setText(QString());
        e61->setText(QString());
        e62->setText(QString());
        e63->setText(QString());
        e64->setText(QString());
        e65->setText(QString());
        e66->setText(QString());
        e67->setText(QString());
        e68->setText(QString());
        e69->setText(QString());
        e70->setText(QString());
        e71->setText(QString());
        e72->setText(QString());
        e73->setText(QString());
        e74->setText(QString());
        e75->setText(QString());
        e76->setText(QString());
        e77->setText(QString());
        e78->setText(QString());
        e79->setText(QString());
        e80->setText(QString());
        e81->setText(QString());
        e82->setText(QString());
        e83->setText(QString());
        e84->setText(QString());
        e85->setText(QString());
        e86->setText(QString());
        e87->setText(QString());
        e88->setText(QString());
        e89->setText(QString());
        e90->setText(QString());
        e91->setText(QString());
        e92->setText(QString());
        e93->setText(QString());
        e94->setText(QString());
        e95->setText(QString());
        e96->setText(QString());
        e97->setText(QString());
        e98->setText(QString());
        e99->setText(QString());
        e100->setText(QString());
        e101->setText(QString());
        e102->setText(QString());
        e103->setText(QString());
        e104->setText(QString());
        e105->setText(QString());
        e106->setText(QString());
        e107->setText(QString());
        e108->setText(QString());
        e109->setText(QString());
        e110->setText(QString());
        e111->setText(QString());
        e112->setText(QString());
        e113->setText(QString());
        e114->setText(QString());
        e115->setText(QString());
        e116->setText(QString());
        e117->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class playground: public Ui_playground {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PLAYGROUND_4_H
